highlighter: pygments

exclude: ['README.md', 'Gemfile', 'notes.txt']

sass:
    sass_dir: _sass
    # Minification
#    style: compressed # for minification


# Site info
domain: quixotic-chris.com
title: Quixotic Chris
author: Chris Cooper
email: chris@quixotic-chris.com
description: "This is the personal site of Chris Cooper."

google_analytics:
    account: UA-47363412-1

disqus:
    account: quixotic-chris
